# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest parameterized flask
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with black
        run: |
          black .
      - name: Test with unittest
        run: |
          python3 -m flask --app app/api.py run &
          flask_pid=$!
          python3 -m unittest
          kill -9 flask_pid
      - name: Show code coverage
        run: |
          python3 -m coverage run -m unittest
          python3 -m coverage report --fail-under=100
